services:
  app:
    container_name: hemis-frontend
    build: .
    expose:
      - "5173"
    networks:
      - web
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://hemis-backend:5000/api}
      - VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL:-http://hemis-backend:5000}
      - VITE_FRONTEND_PORT=${VITE_FRONTEND_PORT:-5173}
      - VITE_BACKEND_PORT=${VITE_BACKEND_PORT:-5000}
      - VITE_CORS_ORIGINS=${VITE_CORS_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173}
      - VITE_TELEMETRY_UPDATE_INTERVAL=${VITE_TELEMETRY_UPDATE_INTERVAL:-1000}
      - VITE_IOT_API_KEY=${VITE_IOT_API_KEY:-your_iot_device_api_key}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-INFO}
      - VITE_NODE_ENV=${VITE_NODE_ENV:-production}
      - VITE_DEBUG=${VITE_DEBUG:-false}
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    user: "1000:1000"

networks:
  web:
    external: true