version: "3.8"

services:
  static-1:
    container_name: static-1
    build: ./static-1
    expose:
      - "8080"
    networks:
      - web

  static-2:
    container_name: static-2
    build: ./static-2
    expose:
      - "8080"
    networks:
      - web

  proxy:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - static-1
      - static-2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - web

networks:
  web:
    driver: bridge
