services:
  app:
    container_name: hemis-backend
    build: .
    expose:
      - "5000"
    networks:
      - web
    env_file:
      - .env
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    user: "1000:1000"

  redis:
    container_name: hemis-redis
    image: redis:7-alpine
    expose:
      - "6379"
    networks:
      - web
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    user: "999:999"

volumes:
  redis_data:

networks:
  web:
    external: true
